### ISSUE TITLE
[BUG] Overlapping Forts on Sado province

### ISSUE THREAD

**Issue by freecsu** [arkhometha/Historical-Project-Mod#104]
**System Information:**
 - Mod Version
0.4.6.2
 - Mod Checksum
DOMS

**Describe the bug**
When forts are built on Niigata and Sado provinces in Japan they both appear on Sado slightly overlapping.

**To Reproduce**
Build forts in Sado and Niigata. 

**Screenshots**
![](https://i.imgur.com/gSToccv.png)

**Comment by arkhometha** [comment]
Hi @freecsu, thanks for the report. This issue was dealt with both in https://github.com/arkhometha/Historical-Project-Mod/commit/cd12d7fa8924c1c6ea9f8ee25a04b0b9d3e8a1a9 and in https://github.com/arkhometha/Historical-Project-Mod/pull/106
So consider it done!
