### ISSUE TITLE
[BUG] Unusual German Territory After Unification w/ Austria

### ISSUE THREAD

**Issue by freecsu** [arkhometha/Historical-Project-Mod#108]
**System Information:**
 - Mod Version
0.4.6.2
 - Mod Checksum
DOMS

**Describe the bug**
Before taking the Three Hurrahs decision as The NGF, Austria had released Hungary in one state (Central Hungary) so when Austria conditionally agreed to join Germany all the other non-German territories were released correctly except Transdanubia, which became a part of Germany. It didn't have German cores but presumably because Hungary was already independent and since Hungary is the only one with cores there nothing else could be done with it. 
The way this works currently maybe this could happen with other states if certain other nations are independent from Austria at the time of formation?

**To Reproduce**
Release Hungary in Central Hungary only, then form Greater Germany with the condition of releasing non-German nations.

As an aside, I disagree with the changes made to greater Germany's territory when formed in the latest patch. The way it worked before, if the player wanted to release Bohemia after formation then they could. It's a lot of infamy to retake Bohemia, and the Sudetenland was considered an integral part of German-speaking Austria, why would they require the new German Empire to release that region along with Bohemia?

**Comment by arkhometha** [comment]
Hi @freecsu, thanks for the report. I can confirm the problem and a fix is coming soon.
In regards to them owning the Sudetes, well, that could be arranged - though I personally think it looks ugly, it makes sense as they start majority German.  They could also keep Bohemia for that matter - the current solution is only temporary as I still need to untangle the mess that is Austrian cores at the start.
