### ISSUE TITLE
[BUG] Lack of trinitrotoluene preventing building of the Panama Canal

### ISSUE THREAD

**Issue by willywaggler** [arkhometha/Historical-Project-Mod#109]
**System Information:**
 - 0.4.6
 - NXES
 - WNVU

**Describe the bug**
Trinitrotoluene is needed to build the Panama Canal, but it suffers from many maluses to researching it from having unemployment, which are practically impossible to avoid if you've a large nation with loads of coal provinces.  This results in a situation where you can have the tech unlocked for decades but never get the invention, and delays the building of the canal greatly. 

**To Reproduce**
Research 'Drilling and Blasting'
Wait to never get the invention

**Expected behavior**
I'm not sure what the best solution to this would be. Plenty of the other coal inventions have unemployment requirements, so maybe just change this one for the sake of the canal, and it probably won't have too much impact on the economy? Or just remove it as a requirement for the decision, perhaps replacing it with something else.

**Comment by arkhometha** [comment]
Hi @willywaggler, thanks for the report. I will move the requirement to the technology, to avoid this hapenning.
