### ISSUE TITLE
Crash when clicking Single Player

### ISSUE THREAD

**Issue by SinisterTrap** [arkhometha/Historical-Project-Mod#141]
Just installed the latest version, dropping the HPM folder and .mod file in the mod folder for Victoria 2. The game loads to menu fine, but once I click on "Single Player" the game immediately crashes. How can I resolve this?

**Comment by ArthurWang10086** [comment]
me too.

**Comment by ArthurWang10086** [comment]
@arkhometha

**Comment by ArthurWang10086** [comment]
@SinisterTrap  
https://www.moddb.com/mods/historical-project-mod/downloads

**Comment by ArthurWang10086** [comment]
@SinisterTrap  
https://www.moddb.com/mods/historical-project-mod/downloads

**Comment by arkhometha** [comment]
Crashes on clicking single player is not an issue I can fix, especially not without checksums reported. I can assure you it works when I click single player so I cannot reproduce it.
