### ISSUE TITLE
[BUG] Tahiti Islands causing permanent war exhaustion

### ISSUE THREAD

**Issue by Wolfenswan** [arkhometha/Historical-Project-Mod#162]
**System Information:**
 - 0.4.6 h3

**Describe the bug**
Four of the Tahiti Islands are always considered 'blockaded', as they lack a harbor, 
prompting a permanent +0.20 WE. 

**Suggestions**
1. Merge islands into existing islands
2. merge them into one and add a harbor.
3. Add/tweak terrain to limit harbor lvl to 1 or 2 for tiny colonial islands.

**Screenshots**
![20200502124041_1](https://user-images.githubusercontent.com/2631302/80862002-20a3fd80-8c72-11ea-9813-6c9f5d3ff706.jpg)
![20200502124304_1](https://user-images.githubusercontent.com/2631302/80862041-737db500-8c72-11ea-8f7c-5cc1d570405d.jpg)

**Additional context**
Possibly related: Tahiti can't be released as a puppet/sattelite.

**Comment by arkhometha** [comment]
Hi @Wolfenswan, thanks for the report. I've reproduced the bug and it has been fixed in commit https://github.com/arkhometha/Historical-Project-Mod/commit/96fb1428559e48843d8df1f74155f013db995605

Thanks agains!
