### ISSUE TITLE
CheckSum

### ISSUE THREAD

**Issue by SeveredSage1** [arkhometha/Historical-Project-Mod#17]
My checksum HHRG but my friends checksum is EMIQ and i've tried reinstalling and uninstalling already the game and mod https://github.com/SighPie/HFM Downloading from here

**Comment by arkhometha** [comment]
Both mods shouldn't be played together. HPM is a standalone mod and trying to play it with other mods that don't support it will not work.
HFM is AFAIK just a variation of an old HPM version. The modder choose to do in a way that this version comes together with it, so new versions of HPM depend on the modder updating his mod.
