### ISSUE TITLE
[BUG] Abolishing serfdom clean up event should not be triggered_only

### ISSUE THREAD

**Issue by Capitanloco6** [arkhometha/Historical-Project-Mod#200]
**System Information:**
 - Mod Version: 0.4637
 - Mod Checksum: PSUP

**Describe the bug**
The event with id 6016825 in CleanUp.txt is set to be "fired_only = yes", yet it has actual triggers coded and nowhere else in the modfiles is there any manual trigger to make it fire. Fired_only should be commented out/deleted in order to make the event work.

**Comment by moretrim** [comment]
`HPM/common/on_actions.txt` references the event:

https://github.com/arkhometha/Historical-Project-Mod/blob/a181b6c01ed76b460bb4a21cb2cedc4aa0c35836/HPM/common/on_actions.txt#L43

 Events that are triggered only and are fired from `on_actions.txt` do have their `trigger` block evaluated, to figure out where they are applicable.

In this case, four times a year, every country checks whether they or a player neighbour needs to adjust some serf pops and if needed, does so accordingly.

**Comment by Capitanloco6** [comment]
Thank you very much for your insight!
