### ISSUE TITLE
[FEATURE] United States loses cores on most of the CSA after the 1870s

### ISSUE THREAD

**Issue by dojiks** [arkhometha/Historical-Project-Mod#212]
The CSA still has USA cores and can be reconquered with constant Restore to Order CB’s. 

**Historical Context**

Would the USA be off the CSA’s back after the Civil War? Probably not. I assume multiple wars and skirmishes would still take place probably till the 1900s. However during the American Civil War in HPM Great Powers such are given the decision to recognize the CSA. 

Would a UK that recognizes the CSA tolerate massive moves against the CSA considering the border between the US and Canada? I assume if they decided to tie themselves to the CSA via recognizing them (probably for economic reasons) I don’t think annexation would be tolerated.

Would a France that recognizes the CSA tolerate annexation? Considering around that time they had a puppet in Mexico to challenge US power in the region [1]. I don't think they would allow Americans to annex the CSA.

**My suggestion**

The US after 1970 (or researching Revolution & Counterrevolution) loses cores on the CSA states that are 90% Dixie (the South as described in this Wikepidia article minus Kentucky [2]) via a CSA decision. This gives the USA one more chance to fully conquer the CSA after the 5 year truce and gives breathing room to a CSA player. 

[1]-https://history.state.gov/milestones/1861-1865/french-intervention
[2]-https://en.wikipedia.org/wiki/Solid_South

**Comment by LoneCrusader2002** [comment]
This is already implemented (with the "Right to Secede" decision for the USA, IIRC). USA AI will take this decision, but must be at peace to do so; so if they're tied up in another war you may have to wait a while for it to happen. Not sure offhand if there are other requirements, but it does work.

**Comment by dojiks** [comment]
Ah ok thank you!
