### ISSUE TITLE
[BUG] Unite with Poland decision bugged

### ISSUE THREAD

**Issue by AVAWeyland** [arkhometha/Historical-Project-Mod#22]
Decision：unite_with_poland

relationship requirement is wrong, as the 50 relationship requirement has to be with POL instead of "THIS".

**Comment by arkhometha** [comment]
Thanks for the report! The decision tries to be dynamic so it can't refer to POL only. This has been fixed in commit https://github.com/arkhometha/Historical-Project-Mod/commit/bb220a37d5c6b28241c87adb80b47de8cc604885
