### ISSUE TITLE
[BUG] Bahrain war against Bahrain, Dismantlement

### ISSUE THREAD

**Issue by freecsu** [arkhometha/Historical-Project-Mod#25]
Playing the latest dev branch as the Ottoman Empire. There's an event in the 1900s where Qatar and Bahrain declare independence (if you have them annexed), this starts two wars, one Ottomans vs Qatar for annexation, and Bahrain vs Bahrain for annexation which obviously never ends, presumably that's meant to be Ottomans vs Bahrain.
![](https://i.imgur.com/ksAZf5T.png)

There's also an issue of the dismantlement event asking if you want to take part or abstain from the dismantlement popping up multiple times, letting you raise or lower your infamy as many times as the event fires. Had this happen when dismantling the USA and Russia, seems to happen when they have no viable colonies to hand out.

**Comment by arkhometha** [comment]
Thanks for the report. I'm doing the proper fixes and investigating the Dismantlement repeat and will push an update for the development branch that fixes these issues shortly!

**Comment by arkhometha** [comment]
Fixed in https://github.com/arkhometha/Historical-Project-Mod/commit/a9984f55990ab54124f0550170ce170a9e92b2e4
