### ISSUE TITLE
[BUG] Savoyian event to cede Savoy for Lombardy is broken

### ISSUE THREAD

**Issue by nivlek-nk** [arkhometha/Historical-Project-Mod#27]
**System Information:**
 - Mod Version: v0.4.5.2
 - Mod Checksum: PHKZ (I used other mod which may alter checksum)
 - Vanilla Checksum: WNVU

**Describe the bug**
When Sardinia-Piedmont breaks apart and becomes Savoy, the event to ask French aid to cede Savoy for Lombardy is broken. The option wrongfully calls the tag of Sardinia-Piedmont instead of Savoy.

**To Reproduce**
See above.

**Expected behavior**
Savoy should be included if Sardinia-Piedmont doesn't exist.

**Screenshots**
![v2_1](https://user-images.githubusercontent.com/55193420/64699401-43ad5180-d4d7-11e9-944e-ea54765d943d.png)

**Comment by arkhometha** [comment]
Thanks a lot for the report!
The issue has been fixed in commit https://github.com/arkhometha/Historical-Project-Mod/commit/cb3bcadba07b2808e9c97e4b9d2999723ffd95d0
