### ISSUE TITLE
[BUG] No opium is being produced on game start

### ISSUE THREAD

**Issue by halcyon-gh** [arkhometha/Historical-Project-Mod#37]
**System Information:**
 - Development branch on 5-nov-2019
 - checksum: DNET

**Describe the bug**
No opium is being produced on game start. No pops are working the resource.
The trade screen indicates no opium is produced anywhere in the world.

**To Reproduce**
Start game as e.g. Thailand, check opium producing province

**Comment by halcyon-gh** [comment]
A closer look shows that this is caused by lack of opium consumption by any pop (all set to 0). Resetting the opium use by pops to previous values solves this issue.

**Comment by arkhometha** [comment]
Hi @halcyon-gh,

Thanks for catching this. Some forgotten leftovers of the upcoming change to how opium works. It's fixed with commit https://github.com/arkhometha/Historical-Project-Mod/commit/84b24c4cf4a9f3d03f9c4bb496571f6a08e32b1f
