### ISSUE TITLE
Delay construction of Panama Canal & Discovery of King Tut's tomb

### ISSUE THREAD

**Issue by rderekp** [arkhometha/Historical-Project-Mod#4]
Both of these events happen far earlier than they did historically in most if not all playthroughs.

For the Panama Canal, I suggest changing the requirement from nitroglycerin to either of the new inventions dynamite or trinitrotoluene, depending on whether or not you believe the first French attempt at the canal would have been successful.

For the discovery of King Tut's tomb, I would recommend just giving it a minimum date to make the discovery more likely around the actual date of 1922.

PS, thanks for the mod and thanks for adding it to GitHub.

**Comment by rderekp** [comment]
I think I figured out how to make a pull request and uploaded my updated canals.txt

**Comment by arkhometha** [comment]
Thanks a lot for the suggestions, @rderekp. I couldn't accept #6  but I merged your changes and credited you in the changelog :smiley:
