### ISSUE TITLE
Countries missing goverment types with Full Citzenship

### ISSUE THREAD

**Issue by SnapperTT** [arkhometha/Historical-Project-Mod#40]
I recently played a few games as a released Australia, and none of the parties had Full Citizenship as a policy. Some of the decisions require FC as a policy. Should every tag have access to at least one government type with Full Citizenship (and all other policies)?

Cheers,
SnapperTT

**Comment by arkhometha** [comment]
Thanks for the bug report! I added FC for the socialists in commit https://github.com/arkhometha/Historical-Project-Mod/commit/afcb7198a1fc2988e2f568283b260f76301f74a4 but any other country that is missing it will keep on missing it. Spotting these things is not easy but yes, all countries should try and have all possible alternatives of policies in one or the other party, in any combination.
