### ISSUE TITLE
[BUG] National Unification CBs are too easy to invalidate

### ISSUE THREAD

**Issue by moretrim** [arkhometha/Historical-Project-Mod#47]
Under some circumstances the unification CBs have a no-sphere requirement:

https://github.com/arkhometha/Historical-Project-Mod/blob/1209fbbf169fd797749b6e2af060348f5caf1982/HPM/common/cb_types.txt#L986

https://github.com/arkhometha/Historical-Project-Mod/blob/1209fbbf169fd797749b6e2af060348f5caf1982/HPM/common/cb_types.txt#L1121

This has the unfortunate side-effect that during an ongoing war a pre-existing CB can easily be invalidated by a GP, leading to player frustration.

Now since the CB also typically requires the attacker to be GP, a forewarned player can stave this off by keeping watch on encroaching GPs and keeping an influence reserve. That being said, this requires game knowledge that's hidden away from players.

I'm not 100% sure why the requirement is here in the first place (guiding the AI? incorporating the influence mini-game into unification wars?), so it's hard for me to recommend a corrective course of action.

**Comment by arkhometha** [comment]
Hi @moretrim, thanks for the report! I agree that this can be highly frustrating to the player, as wars ending out for no reason (other than the CB going invalid) is frustrating, to say the least.

IIRC the requirement is NNM legacy. I could either remove it or add an OR with war_with, which should keep the wars going to the end even if the country get sphered. Or it might just be simpler to remove the requirement altogether...

**Comment by moretrim** [comment]
On closer look I've had trouble reproducing the CB invalidation so this might have been a red herring. I'll be on the lookout for more invalidations in the future in order to figure out what's happening.
