### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Wolfenswan** [arkhometha/Historical-Project-Mod#53]
**System Information:**
 - mod 0.4.6

**Describe the bug**
Treasury keeps resetting to exactly 0 each month. I noticed roughly after I started building the suez canal as Sweden and activated the decision on the Scandinavia-"chain" that puppets the norway & denmark.
I am not 100% this is a bug, depending on how the canal loans are supposed to work.

**Comment by arkhometha** [comment]
Not a bug, part of the debt system. Go [here](https://github.com/arkhometha/Historical-Project-Mod/wiki/Game-Mechanics#21-the-debt-system) for more information. I should add a minimum amount of money you need for these buildings even for GPs, to avoid this confusion.
