### ISSUE TITLE
[BUG] No localization text for luxury factory inventions

### ISSUE THREAD

**Issue by CommandoGrandma** [arkhometha/Historical-Project-Mod#59]
Playing on the beta hotfix. The descriptions for the new luxury furniture and luxury clothes factory inventions are placeholder text.

**Comment by arkhometha** [comment]
Hi @CommandoGrandma, thanks for the report. The popup for the invention shouldn't even show up, or so I thought, but anyway, this is fixed in commit https://github.com/arkhometha/Historical-Project-Mod/commit/be39d4e7b2abfb755a98cde18490ad2c9f2fff43
