### ISSUE TITLE
Canal Debt Working as Intended?

### ISSUE THREAD

**Issue by freecsu** [arkhometha/Historical-Project-Mod#67]
The amount of debt the player must owe to make even the minimum payment on Suez can send them into debt repayment for an entire decade, and that's with a healthy economy. Meanwhile the minimum payment to build the Panama canal is so high I can only assume the player will be still be making payments until 1936 with how late into the game the canal is built and how long it takes to generate 10M pounds, I dread to think how long the full 30M would take. The entire time your economy is capped at 10k pounds you are also incurring massive debt with other nations so even after you have paid the 10M you owe you will probably also owe a few million to everyone else as well. Is this how it is intended to work?

**Comment by Wolfenswan** [comment]
I also wrote a bit about this: https://github.com/arkhometha/Historical-Project-Mod/issues/57
Imho it's a general issue with an otherwise good idea.
