### ISSUE TITLE
[BUG]unable to start flashpoint crisis in finland over swedens core even if enabled from start.

### ISSUE THREAD

**Issue by alexmannen** [arkhometha/Historical-Project-Mod#69]
**System Information:**
 - Mod Version 4.6beta
 - Mod Checksum
 - Vanilla Checksum

**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. Save games can also be useful.

**Additional context**

**Comment by arkhometha** [comment]
Hi @alexmannen, the game itself doesn't consider these places flashpoints. I think it's because they are finish cores with majority finish, but I can't alter that at all. It's a hardcoded part of the system and flashpoints just show up in the region if Russia owns it.
