### ISSUE TITLE
[BUG] The 0.4.6 beta2 release is missing the .mod file

### ISSUE THREAD

**Issue by moretrim** [arkhometha/Historical-Project-Mod#74]
Nothing too serious, the `HPM.v0.4.6b2.7z` archive is missing `HPM.mod`.

People that are affected can work around the issue by downloading [the file individually](https://raw.githubusercontent.com/arkhometha/Historical-Project-Mod/v0.4.6-beta2/HPM.mod).

**Comment by arkhometha** [comment]
Hey @moretrim, thanks for the report. I noticed myself some days ago. Made sure the new version has .mod file.
