### ISSUE TITLE
[BUG] States not released as slave states

### ISSUE THREAD

**Issue by Libeccio-DD** [arkhometha/Historical-Project-Mod#96]
**System Information:**
 - Mod Version v0.4.6 - Hotfix 2
 - Mod Checksum WWYQ
 - Vanilla Checksum WNVU

**Describe the bug**
Whenever a country with slavery releases another country which gives them slave states, these slave states instead are sometimes turned into free states. For example when Sudan gets released the states Dongola, Sudan and Kordofan which were previously slave states, are now either free or slave states. This is random and in the example of Sudan sometimes Dongola get released as free state and sometimes as slave state.

This bug also affects countries that get released though events. When Zanzibar gets released by Oman from the death of the Sultan event, not all of its states remain slave states. For example sometimes Kenya becomes a free state and sometimes it remains a slave state.

**To Reproduce**
Play as a country with slave states that can be released to another country and then release that country. Egypt and Oman are good ways to reproduce this bug.

**Expected behavior**
Slave states should remain slave states after a released country gets them.

**Screenshots**
If applicable, add screenshots to help explain your problem. Save games can also be useful.

**Additional context**

**Comment by arkhometha** [comment]
Hi @Libeccio-DD, thanks for the report. I can confirm the bug - it seems to happen only in events. I will explore what could be causing it and fix it.
